name: Build and Push Docker Back Image

on:
  push:
    branches:
      - main
    paths:
      - 'back/**'
  pull_request:
    paths:
      - 'back/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata for backend
        id: meta-backend
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.DOCKER_USERNAME }}/backend

      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./back
          file: ./back/Dockerfile.backend
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-backend.outputs.tags }}
          annotations: ${{ steps.meta-backend.outputs.annotations }}
          provenance: true
          sbom: true
