name: Ci Sonar back

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

on:
  push:
    branches: [main]
    paths:
      - 'back/**'
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'back/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Récupération du code
    - name: Checkout du code
      uses: actions/checkout@v3

    # Installation de Java
    - name: Setup JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    # Build & test du backend (Spring Boot)
    - name: Build et tests backend
      run: |
        cd back
        mvn test
        mvn jacoco:report

    # Couverture backend
    - name: Upload rapport de couverture Java
      uses: actions/upload-artifact@v4  
      with:
        name: couverture-java
        path: back/target/site/jacoco/

  
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build and analyze
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        cd back
        mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.organization=mammuth169 \
          -Dsonar.projectKey=yann-rethore-BobApp-Back-End
