name: Ci Test front

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

on:
  push:
    branches: [main]
    paths:
      - 'front/**'
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'front/**'
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Récupération du code
    - name: Checkout du code
      uses: actions/checkout@v4

      # Installation de Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

   # Tests Angular + couverture
    - name: Install & test frontend
      run: |
        cd front
        npm install
        npm run test -- --watch=false --code-coverage --browsers ChromeHeadless

   # Couverture frontend
    - name: Upload rapport de couverture Angular
      uses: actions/upload-artifact@v4
      with:
        name: couverture-angular
        path: front/coverage/  
        
