name: Ci Test back

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    

jobs:
  CI-Test-back-test:
    runs-on: ubuntu-latest

    steps:
    # Récupération du code
    - name: Checkout du code
      uses: actions/checkout@v3

    # Installation de Java
    - name: Setup JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    # Build & test du backend (Spring Boot)
    - name: Build et tests backend
      run: |
        if ! git diff --name-only origin/main | grep -q '^back/'; then
            echo "No front-end changes. Skipping tests."
            exit 0
          fi
        echo "Running tests..."
        cd back
        mvn test
        mvn jacoco:report

    # Couverture backend
    - name: Upload rapport de couverture Java
      uses: actions/upload-artifact@v4  
      with:
        name: couverture-java
        path: back/target/site/jacoco/

