name: Déploiement manuel

on:
  workflow_dispatch:  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Déploiement Docker Compose
        run: |
          docker compose -f docker-compose.yml up -d
