name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      #  Metadata for backend
      - name: Extract metadata for backend
        id: meta-backend
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.DOCKER_USERNAME }}/bobapp/backend

      # Metadata for frontend
      - name: Extract metadata for frontend
        id: meta-frontend
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.DOCKER_USERNAME }}/bobapp/frontend

      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./back
          file: ./back/Dockerfile.backend
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-backend.outputs.tags }}
          annotations: ${{ steps.meta-backend.outputs.annotations }}
          provenance: true
          sbom: true

      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./front
          file: ./front/Dockerfile.frontend
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-frontend.outputs.tags }}
          annotations: ${{ steps.meta-frontend.outputs.annotations }}
          provenance: true
          sbom: true
