name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v3

    - name: Setup JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Build backend (Spring Boot)
      run: |
        cd back
        mvn clean install

    - name: Setup Node.js pour Angular
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Build frontend (Angular)
      run: |
        cd front
        npm install
        npm run build
