name: SonarQube
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_run:
    workflows: ["Simple build","Test and Cover"]
    types:
      - completed

jobs:
  sonar-analysis:
    name: Unified SonarQube Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Install Node (pour le frontend)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Build backend and generate test reports
        run: |
          cd back
          mvn clean verify
          cd ..

      - name: Build frontend and generate coverage
        run: |
          cd front
          npm ci
          npm run test -- --code-coverage
          cd ..

      - name: Install SonarQube Scanner
        run: |
            npm install -g sonar-scanner

      - name: Run SonarQube analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner -Dsonar.login=${{ secrets.SONAR_TOKEN }}
