name: Test and Cover

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Récupération du code
    - name: Checkout du code
      uses: actions/checkout@v3

    # Installation de Java
    - name: Setup JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    # Build & test du backend (Spring Boot)
    - name: Build et tests backend
      run: |
        cd back
        mvn test
        mvn jacoco:report

    # Couverture backend
    - name: Upload rapport de couverture Java
      uses: actions/upload-artifact@v4  
      with:
        name: couverture-java
        path: back/target/site/jacoco/

    # Installation de Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

   # Tests Angular + couverture
    - name: Install & test frontend
      run: |
        cd front
        npm install
        npm run test -- --watch=false --code-coverage --browsers ChromeHeadless

   # Couverture frontend
    - name: Upload rapport de couverture Angular
      uses: actions/upload-artifact@v4
      with:
        name: couverture-angular
        path: front/coverage/    

  # affichage des resultats
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: |
                back/target/surefire-reports/*.xml
                front/test-report.xml
