name: CI - Tests et Couverture

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Récupération du code
    - name: Checkout du code
      uses: actions/checkout@v3

    # Installation de Java
    - name: Setup JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    # Build & test du backend (Spring Boot)
    - name: Build et tests backend
      run: |
        cd back
        mvn test
        mvn jacoco:report

    # Couverture backend
    - name: Upload rapport de couverture Java
      uses: actions/upload-artifact@v4  
      with:
        name: couverture-java
        path: back/target/site/jacoco/

    # Couverture backend pour affichage dans github actaion
    - name: Report Jacoco (back)
      uses: dorny/test-reporter@v2
      if: ${{ always() }}
      with:
        name: Tests Java
        path: target/test-reports/junit.xml
        reporter: java-junit
        use-actions-summary: true

    # Installation de Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

   # Tests Angular + couverture
    - name: Install & test frontend
      run: |
        cd front
        npm install
        npm run test -- --watch=false --code-coverage --browsers ChromeHeadless

   # Couverture frontend
    - name: Upload rapport de couverture Angular
      uses: actions/upload-artifact@v4
      with:
        name: couverture-angular
        path: front/coverage/    

     # Couverture frontend pour affichage dans github actaion
    - name: Report Karma (front)
      uses: dorny/test-reporter@v2
      if: ${{ always() }}
      with:
        name: Tests Angular
        path: coverage/karma/junit-report.xml
        reporter: jest-junit # ou mocha-junit selon ton setup
        use-actions-summary: true
